name: flutter_alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 1.1.2
homepage: https://github.com/hautvfami/flutter-alice

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dio: ^5.6.0
  chopper: ^8.0.1+1
  overlay_support: ^2.1.0
  share_plus: ^10.0.2
  rxdart: ^0.28.0
